"""add payment_link and gateway fields on payments

Revision ID: b9af8c85f6c2
Revises: ff8d5465ffe8
Create Date: 2026-09-02 12:38:38.800713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9af8c85f6c2'
down_revision: Union[str, Sequence[str], None] = 'ff8d5465ffe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('provider', sa.String(length=30), nullable=True),
    sa.Column('provider_order_id', sa.String(length=100), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_links_business_id'), 'payment_links', ['business_id'], unique=False)
    op.create_index(op.f('ix_payment_links_id'), 'payment_links', ['id'], unique=False)
    op.create_index(op.f('ix_payment_links_invoice_id'), 'payment_links', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_links_provider_order_id'), 'payment_links', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payment_links_status'), 'payment_links', ['status'], unique=False)
    op.create_index(op.f('ix_payment_links_token'), 'payment_links', ['token'], unique=True)
    op.add_column('payments', sa.Column('payment_link_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('business_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('payments', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('payments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('payments', sa.Column('provider', sa.String(length=30), nullable=True))
    op.add_column('payments', sa.Column('provider_order_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('provider_payment_id', sa.String(length=100), nullable=True))
    op.add_column('payments', sa.Column('signature_verified', sa.Boolean(), nullable=True))
    op.add_column('payments', sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('payments', sa.Column('raw_event', sa.JSON(), nullable=True))
    op.create_index(op.f('ix_payments_business_id'), 'payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_link_id'), 'payments', ['payment_link_id'], unique=False)
    op.create_index(op.f('ix_payments_provider'), 'payments', ['provider'], unique=False)
    op.create_index(op.f('ix_payments_provider_order_id'), 'payments', ['provider_order_id'], unique=False)
    op.create_index(op.f('ix_payments_provider_payment_id'), 'payments', ['provider_payment_id'], unique=True)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_foreign_key(None, 'payments', 'customers', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'payment_links', ['payment_link_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'businesses', ['business_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_provider'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_link_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_business_id'), table_name='payments')
    op.drop_column('payments', 'raw_event')
    op.drop_column('payments', 'verified_at')
    op.drop_column('payments', 'signature_verified')
    op.drop_column('payments', 'provider_payment_id')
    op.drop_column('payments', 'provider_order_id')
    op.drop_column('payments', 'provider')
    op.drop_column('payments', 'status')
    op.drop_column('payments', 'currency')
    op.drop_column('payments', 'customer_id')
    op.drop_column('payments', 'business_id')
    op.drop_column('payments', 'payment_link_id')
    op.drop_index(op.f('ix_payment_links_token'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_status'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_provider_order_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_invoice_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_id'), table_name='payment_links')
    op.drop_index(op.f('ix_payment_links_business_id'), table_name='payment_links')
    op.drop_table('payment_links')
    # ### end Alembic commands ###
